server:
  ws_url: 'wss://api-dev-mosaic.acslgcs.com'
  auth:
    type: 'simple-token'
    robot_id: '42082865-34a3-40c1-bea7-e321622d8c39'
    params:
      token: 'lBJJzdR2NdzMH7KPL+tWjuuCUmCsA1wtkMIfNPqeGqqA9JQGhr1WaejLt2xdqTVG8DN5Y2bSabj8taGpuuDLuK8Yx/iOQrcMRbPshrvyljU=.aTtdzHW3TngTHqJQk7dqGhaSyi4hFm88/YS4rpBELxg='
  webrtc:
    ice_servers:
      - urls:
          - 'turn.acslgcs.com:3478'
        username: '#####'
        credential: '#####'

connectors:
  - type: 'opencv-sender-camera'
    label: 'camera_stream'
    params:
      fps: 30
      camera_id: 0
      width: 640
      height: 480

  - type: 'turtlebot-sender-laser-scan'
    label: 'laser_scan'

  - type: 'turtlebot-receiver-teleop'
    label: 'teleop'
